name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore
      working-directory: RconSharp

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: RconSharp

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: RconSharp